[package]
name = "rust-tracer"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_tracer"
path = "src/lib.rs"

[dependencies]
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rayon = "1.7"
